class Shaeri {
  final shaeriTime = [
    {
      "shaeriShuedle": [
        {
          "index": "1",
          "day": "রবিবার",
          "date": "03 April",
          "Shari_time": "04:27 AM",
          "ifatar_time": "06:19 PM",
        },
        {
          "index": "2",
          "day": "সোমবার",
          "date": "04 April",
          "Shari_time": " 04:26 AM",
          "ifatar_time": "06:19 PM",
        },
        {
          "index": "3",
          "day": "মঙ্গলবার",
          "date": "05 April",
          "Shari_time": "04:25 AM",
          "ifatar_time": "06:20 PM",
        },
        {
          "index": "4",
          "day": "বুধবার",
          "date": "06 April",
          "Shari_time": "04:24 AM",
          "ifatar_time": "06:20 PM",
        },
        {
          "index": "5",
          "day": "বূহস্পতিবার",
          "date": "07 April",
          "Shari_time": "04:23 AM",
          "ifatar_time": "06:21 PM",
        },
        {
          "index": "6",
          "day": "শুক্রবার",
          "date": "08 April",
          "Shari_time": "04:22 AM",
          "ifatar_time": "06:21 PM",
        },
        {
          "index": "7",
          "day": "শনিবার",
          "date": "09 April",
          "Shari_time": "04:21 AM",
          "ifatar_time": "06:22 PM",
        },
        {
          "index": "8",
          "day": "রবিবার",
          "date": "10 April",
          "Shari_time": "04:20 AM",
          "ifatar_time": "06:22 PM",
        },
        {
          "index": "9",
          "day": "সোমবার",
          "date": "11 April",
          "Shari_time": "04:19 AM",
          "ifatar_time": "06:22 PM",
        },
        {
          "index": "10",
          "day": "মঙ্গলবার",
          "date": "12 April",
          "Shari_time": "04:18 AM",
          "ifatar_time": "06:23 PM",
        },
        {
          "index": "11",
          "day": "বুধবার",
          "date": "13 April",
          "Shari_time": "04:16 AM",
          "ifatar_time": "06:23 PM",
        },
        {
          "index": "12",
          "day": "বূহস্পতিবার",
          "date": "14 April",
          "Shari_time": "04:15 AM",
          "ifatar_time": "06:23 PM",
        },
        {
          "index": "13",
          "day": "শুক্রবার",
          "date": "15 April",
          "Shari_time": "04:14 AM",
          "ifatar_time": "06:24 PM",
        },
        {
          "index": "14",
          "day": "শনিবার",
          "date": "16 April",
          "Shari_time": "04:13 AM",
          "ifatar_time": "06:24 PM",
        },
        {
          "index": "15",
          "day": "রবিবার",
          "date": "17 April",
          "Shari_time": "04:12 AM",
          "ifatar_time": "06:24 PM",
        },
        {
          "index": "16",
          "day": "সোমবার",
          "date": "18 April",
          "Shari_time": "04:11 AM",
          "ifatar_time": "06:25 PM",
        },
        {
          "index": "17",
          "day": "মঙ্গলবার",
          "date": "19 April",
          "Shari_time": "04:10 AM",
          "ifatar_time": "06:25 PM",
        },
        {
          "index": "18",
          "day": "বুধবার",
          "date": "20 April",
          "Shari_time": "04:09 AM",
          "ifatar_time": "06:26 PM",
        },
        {
          "index": "19",
          "day": "বূহস্পতিবার",
          "date": "21 April",
          "Shari_time": "04:08 AM",
          "ifatar_time": "06:26 PM",
        },
        {
          "index": "20",
          "day": "শুক্রবার",
          "date": "22 April",
          "Shari_time": "04:07 AM",
          "ifatar_time": "06:27 PM",
        },
        {
          "index": "21",
          "day": "শনিবার",
          "date": "23 April",
          "Shari_time": "04:06 AM",
          "ifatar_time": "06:27 PM",
        },
        {
          "index": "22",
          "day": "রবিবার",
          "date": "24 April",
          "Shari_time": "04:05 AM",
          "ifatar_time": "06:28 PM",
        },
        {
          "index": "23",
          "day": "সোমবার",
          "date": "25 April",
          "Shari_time": "04:05 AM",
          "ifatar_time": "06:28 PM",
        },
        {
          "index": "24",
          "day": "মঙ্গলবার",
          "date": "26 April",
          "Shari_time": "04:04 AM",
          "ifatar_time": "06:29 PM",
        },
        {
          "index": "25",
          "day": "বুধবার",
          "date": "27 April",
          "Shari_time": "04:03 AM",
          "ifatar_time": "06:29 PM",
        },
        {
          "index": "26",
          "day": "বূহস্পতিবার",
          "date": "28 April",
          "Shari_time": "04:02 AM",
          "ifatar_time": "06:29 PM",
        },
        {
          "index": "27",
          "day": "শুক্রবার",
          "date": "29 April",
          "Shari_time": "04:01 AM",
          "ifatar_time": "06:30 PM",
        },
        {
          "index": "28",
          "day": "শনিবার",
          "date": "30 April",
          "Shari_time": "04:00 AM",
          "ifatar_time": "06:30 PM",
        },
        {
          "index": "29",
          "day": "রবিবার",
          "date": "01 May",
          "Shari_time": "03:59 AM",
          "ifatar_time": "06:31 PM",
        },
        {
          "index": "30",
          "day": "সোমবার",
          "date": "02 May",
          "Shari_time": "03:58 AM",
          "ifatar_time": "06:31 PM",
        },
      ]
    }
  ];
}
